version: "3"

services:
    db:
        build: docker/psql
        restart: always
        ports: 
            - "5432:5432"
        environment:
            - DB_HOST
            - DB_USER
            - DB_NAME
            - DB_PASSWORD
        volumes:
            - "/var/lib/mailape/psql/data:/var/lib/postgresql/data"
    web:
        build: .
        ports:
            - "80:80"
        env_file:
            - .env
    redis:
        image: "redis:alpine"
        ports: 
        - "6379:6379"
        volumes:
            - "/var/lib/mailape/redis/data:/data"
        command: redis-server --appendonly yes
