#!/usr/bin/env bash

root=$1
source $root/venv/bin/activate

export SECRET_KEY=FAKE_KEY
export DB_PASSWORD=FAKE_PASS
export SETTINGS_MODULE=mailape.settings
export EMAIL_HOST=EMAIL_HOST
export EMAIL_HOST_USER=EMAIL_HOST_USER
export EMAIL_PASSWORD=EMAIL_PASSWORD
export MAILING_LIST_FROM_EMAIL=MAILING_LIST_FROM_EMAIL
export MAILING_LIST_LINK_DOMAIN=MAILING_LIST_LINK_DOMAIN
export CELERY_BROKER_URL=CELERY_BROKER_URL
export CELERY_RESULT_BACKEND=CELERY_RESULT_BACKEND

cd $root
python manage.py collectstatic
